#!/usr/bin/env groovy

pipeline {

	stages {
		agent {
			label 'any'
		}
		stage('Build Custom Docker Image') {
			agent {
				label 'built-in'
			}
			steps {
				script {
					dir("Day5/build-custom-image-using-playbook") {
						sh "ansible-playbook playbook.yml"
					}
				}
			}
		}
		stage('Compile') {
			agent {
				label 'jenkins-docker-slave'
			}
			steps {
				script {
					dir("Day5/multi-module-project") {
						sh "mvn clean compile"
					}
				}
			}
		}
		stage('Unit Test') {
			agent {
				label 'jenkins-docker-slave'
			}
			steps {
				script {
					dir("Day5/multi-module-project") {
						sh "mvn test -P test"
					}
				}
			}
		}
		stage('Package') {
			agent {
				label 'jenkins-docker-slave'
			}
			steps {
				script {
					dir("Day5/multi-module-project") {
						sh "mvn package -P package"
					}
				}
			}
		}
		stage('Install') {
			agent {
				label 'jenkins-docker-slave'
			}
			steps {
				script {
					dir("Day5/multi-module-project") {
						sh "mvn install -P install"
					}
				}
			}
		}
		stage('Deploy') {
			agent {
				label 'jenkins-docker-slave'
			}
			steps {
				script {
					dir("Day5/multi-module-project") {
						sh "mvn deploy -P deploy"
					}
				}
			}
		}
	}
}
