#!/usr/bin/env groovy

pipeline {
	agent none 
	stages {
		stage('Build Custom Docker Image') {
			agent {
				label 'built-in'
			}
			steps {
				script {
					dir("Day5/build-custom-image-using-playbook") {
						sh "ansible-playbook playbook.yml"
					}
				}
			}
		}
		stage('Compile') {
			agent {
				label 'jenkins-slave'
			}
			steps {
				script {
					dir("Day5/multi-module-project") {
						sh "mvn clean compile"
					}
				}
			}
		}
		stage('Unit Test') {
			agent {
				label 'jenkins-slave'
			}
			steps {
				script {
					dir("Day5/multi-module-project") {
						sh "mvn test"
					}
				}
			}
		}
		stage('Package') {
			agent {
				label 'jenkins-slave'
			}
			steps {
				script {
					dir("Day5/multi-module-project") {
						sh "mvn package"
					}
				}
			}
		}
		stage('Install') {
			agent {
				label 'jenkins-slave'
			}
			steps {
				script {
					dir("Day5/multi-module-project") {
						sh "mvn install"
					}
				}
			}
		}
	}
}
